### ISSUE TITLE
Sound issue

### ISSUE THREAD

**Issue by vrcod** [raphael/linux-samus#34] opened 2015-08-16 18:54 UTC
There was this issue before with headphone volume being low and left and right channels mixed up. I've just updated and compiled the kernel, ran sound.sh and the headphones seem to be working fine. However, now I have the exact same issue with laptop speakers - the volume on max is very quiet and left and right channels are mixed up. It was working fine before. A config issue maybe?

**Comment by raphael** [comment] 2015-08-18 03:54
I can confirm that behavior... seems related to the alsa state :( Not sure what to try next, open to suggestions :)

**Comment by nskaggs** [comment] 2015-08-18 14:21
Ugh, ;-( I too can confirm sadly. I was trying to watch something yesterday and thought the audio in the clip was just really really low. I was attempting to boost it to no avail. Checking things now confirm this is reminiscent of the headphone issue.

**Comment by raphael** [comment] 2015-09-02 17:33
Closing this as duplicate of #33

**Closed by raphael** 2015-09-02 17:33 UTC
