### ISSUE TITLE
no suspend?

### ISSUE THREAD

**Issue by recri** [raphael/linux-samus#122] opened 2016-03-11 19:08 UTC
Running 4.4.5 according to uname -a.

Suspending by closing lid.  The cover LED's remain lit in the Blue-Red-Yellow-Green operational pattern.  The screen is black when the cover is reopened.  The screen remains black because the computer doesn't return from suspend.  Pressing the power button doesn't resume from suspend.   Have to recover by force kill, 20 seconds on the power button, then the machine cold boots when the power button is pressed again.

This may have been present in earlier releases.  I've been doing power down and cold start recently, but I decided to check suspend this morning.

**Comment by mjrosencrantz** [comment] 2016-03-11 19:25
I'm having this problem as well.  Also, the fan seems to be running like the cpu is doing something.

**Comment by remexre** [comment] 2016-03-12 22:08
I'm having this issue as well. Further information though -- it doesn't happen for `swsusp` level `freeze`, but it does for the others.

**Comment by Ivan0xFF** [comment] 2016-03-13 00:19
I can confirm. The pixel won't properly go to sleep when closing the lid, and then will be stuck on a black screen that you are unable to wake up from when re-opening it.

**Comment by raphael** [comment] 2016-03-13 00:26
My Pixel SSD died yesterday :( I'm hoping Google can replace it but running developer mode may void the warranty. I am not able to do anything until that gets resolved...

**Comment by recri** [comment] 2016-03-13 01:32
Oh, so sorry to hear.

But on the bright side I just RMA'd my Pixel because of fan noise, and
there was no evidence of developer mode on the machine I sent back to them,
because they told me to powerwash it before sending it back.  I guess it's
harder to powerwash with a dead SSD, but they aren't going to be looking at
the contents, either.  Takes about a week to get the replacement assuming
you have the credit to authorize a payment in the event you fail to return
your problematic machine.

By the way, the first replacement they sent was useless, band of
malfunctioning pixels an inch and a half tall across the screen.  That's a
66% failure rate from my perspective.  But the fan on this one is so quiet
I never hear it, and the keyboard seems to be better quality, too.

-- rec --

**Comment by AdaRoseEdwards** [comment] 2016-03-13 02:02
@raphael My SSD died the other day too. The first thing they asked when I told them was, 'Was it running Linux, so perhaps it is an issue?'. Got a replacement, will leave it on cros (but dev mode) for now as I am a little scared to damage this one as I can't afford to replace it.

**Comment by godlikemouse** [comment] 2016-03-13 21:36
I'm having the same issue, didn't have the issue with the previous kernel version.  I'm still trying to figure out how to fix the issue, maybe I'll roll the kernel back to the previous version.

**Comment by gatorpatch** [comment] 2016-03-14 00:37
Have the same issue, rolling back until fixed.

**Comment by sprc** [comment] 2016-03-14 03:25
Same. I compiled mainline linux-stable 4.4.5 and it doesn't exhibit the same behaviour so there's presumably something in the extra patching that's causing the problem. I also recompiled without recent lightbar patch I recently submitted, since this is the first version with it actually in the build, but the problem persisted so thankfully I am blameless. :)

I did notice it gets past the point where it unmounts things and shuts down USB peripherals; the light on the USB drive I have Ubuntu installed on turns all the way off, whereas it normally "breathes" while idle.

**Comment by daspliff** [comment] 2016-03-14 05:30
Also confirming suspend bug. Pixel stuck on a black screen when waking up from suspend.  Just upgraded to 4.4.5

**Comment by SimionKreimer** [comment] 2016-03-14 22:37
I'm also seeing the suspend bug. What is the best way to roll back in archlinux, the downgrade command doesn't seem to work?

**Comment by gatorpatch** [comment] 2016-03-14 22:58
Download this:
https://aur.archlinux.org/cgit/aur.git/commit/?h=linux-samus4&id=1ffea3eafbd4be7e8ce5fa1ba95532307fbe9b77
Then unzip it, go to the folder in terminal and run makepkg -sri

**Comment by aeroevan** [comment] 2016-03-15 00:55
for people having SSD issues, were you running FwRev=S9FM02.3 (hdparm -i /dev/sda)?

see https://bbs.archlinux.org/viewtopic.php?pid=1587933#p1587933

**Comment by SimionKreimer** [comment] 2016-03-15 03:33
@gatorpath, worked like charm, thanks for helping a newb out :)

**Comment by godlikemouse** [comment] 2016-03-15 03:48
@gatorpatch Awesome, thanks for sharing that.

**Comment by daspliff** [comment] 2016-03-15 11:59
How can I roll back in Ubuntu 15.10?

**Comment by ehegnes** [comment] 2016-03-15 12:04
@AdaRoseEdwards, that's a great insight! Your experience, coupled with @aeroevan's citing of the firmware update used by the Chromium folk, at least raises the question of whether or not the firmware is partially to blame.

I've hacked at some internal ChromiumOS code and converted the hexadecimal firmware update back into a binary blob for flashing via `hdparm`. I'm personally waiting until my finals are over to take the time in backing up and flashing (a firmware update would wipe the SSD), but I'd be glad to test first and publish the code in the case that anybody else would like to update.

**Comment by ehegnes** [comment] 2016-03-15 12:08
@daspliff, you can download a [tagged release](https://github.com/raphael/linux-samus/tags), decompress, and install as you normally would.

Alternatively, if you have the repo cloned, you can checkout a tag with `git checkout <tag>` and proceed in a similar fashion.

**Comment by recri** [comment] 2016-03-15 15:26
My new replacement Pixel arrived two weeks ago with FwRev=S9FM02.3
installed on it.

-- rec --

**Comment by remexre** [comment] 2016-03-15 19:06
@ehegnes I'm willing to guinea-pig that later today, if you want.

**Comment by ehegnes** [comment] 2016-03-15 19:51
@remexre, you are brave. There be dragons ahead/use at your own risk, and all that. If I were you (when I'm you in a few days), I'd `dd` my drive as a backup and run this command from a LiveCD with the device unmounted.

Firmware Blob: [firmware-ssd-02.3.bin](https://gist.github.com/ehegnes/92ed8fe0078294b71ec6/raw/f565b2ad326747665b92ba1325b558de75399735/firmware-ssd-02.3.bin)
MD5SUM: `5cbc5c2da4bed35ea499d18dbde6d295`
Command:
```shell
sudo hdparm --fwdownload-mode7 "/path/to/firmware.bin" --yes-i-know-what-i-am-doing --please-destroy-my-drive "/dev/sda"
```

This should all, presumably, work. I'm really not sure. :)

**Comment by raphael** [comment] 2016-03-15 22:14
Good news! Google has agreed to do a "courtesy one time replacement" :) So I should have a functioning Pixel in a week or so.

**Comment by ehegnes** [comment] 2016-03-15 22:34
@raphael that's great news! Maybe the Google folk are taking it easy on the maintainer of `linux-samus`. ;)

Hopefully you won't have to try the dangerous magic above to update your firmware, as your replacement will come fully updated.

**Comment by remexre** [comment] 2016-03-16 01:13
@ehegnes
```

/dev/sda:
fwdownload: xfer_mode=7 min=1 max=65535 size=461312
FAILED: Input/output error
```

I'm still able to boot though?

**Comment by recri** [comment] 2016-03-16 01:38
Hmm, you didn't by any chance put the disk into firmware loading mode then
try to read the new firmware off the same disk?  Seems like that would be
allowed to generate an Input/output error.

-- rec --

**Comment by remexre** [comment] 2016-03-16 01:40
Uhhhhh... how would I go about doing that? I ran the command above, got the error, and tried mounting sda to check for breakage. No breakage, but `hdparm -i /dev/sda` (after rebooting) reports:
```
/dev/sda:

 Model=KINGSTON RBU-SUS151S364GD, FwRev=S9FM01.8, SerialNo=50026B7E51005F7D
 Config={ Fixed }
 RawCHS=16383/16/63, TrkSize=0, SectSize=0, ECCbytes=0
 BuffType=unknown, BuffSize=unknown, MaxMultSect=16, MultSect=16
 CurCHS=16383/16/63, CurSects=16514064, LBA=yes, LBAsects=125045424
 IORDY=on/off, tPIO={min:120,w/IORDY:120}, tDMA={min:120,rec:120}
 PIO modes:  pio0 pio3 pio4 
 DMA modes:  mdma0 mdma1 mdma2 
 UDMA modes: udma0 udma1 udma2 udma3 udma4 udma5 *udma6 
 AdvancedPM=yes: disabled (255) WriteCache=enabled
 Drive conforms to: Unspecified:  ATA/ATAPI-3,4,5,6,7

 * signifies the current active mode
```

**Comment by ehegnes** [comment] 2016-03-16 01:58
@remexre well \*phew\*, at least it didn't brick your SSD?

I'll look into this more thoroughly.

**Comment by sprc** [comment] 2016-03-16 04:23
Patched 4.4.3 is unaffected by the suspend issue; 4.4.4 and 4.4.5 are affected. The automatically-generated patch currently fails to apply to 4.5.

We might want to move discussion of the SSD issue to a unique thread to make it easier to find/track since it's presumably not related to the suspend issue.

**Comment by vadixidav** [comment] 2016-03-16 07:13
Not sure if it matters, but I am getting this suspend issue with release 4.4-7. I was using 4.4-5 earlier and that didn't cause this issue. Had an uptime of about 40 days. I guess I will temporarily just shutdown the laptop completely when moving. Closing the lid while its on makes the keys get pressed randomly, so I try to avoid that.

**Comment by sprc** [comment] 2016-03-16 14:26
@vadixidav - that makes sense; the linux-samus repo version 4.4-7 uses kernel version 4.4.5, whereas repo version 4.4-5 used kernel version 4.4.1.

**Comment by aaron235** [comment] 2016-03-21 05:26
Yeah, I've also had a dead SSD. They don't like to take it back, it took a huge fuss. I'm running off of a USB stick now. I'm a little worried that they included junk SSDs because it was supposed to be a web machine with minimal disk writes.

I'm also experiencing the issue with the failure to sleep. Any solution yet other than to roll back?

**Comment by sprc** [comment] 2016-03-21 19:04
Should we update repo to use a 4.4.3 kernel until we are able to pin down the suspend issue and/or get 4.5.x working?

**Comment by raphael** [comment] 2016-03-21 20:42
I'll look into the issue as soon as I can. My "new" Pixel is supposed to arrive tomorrow so I should be able to look into it by the end of the week.

**Comment by funkaster** [comment] 2016-03-22 01:19
same here. No dead SSD, but suspend is not working. Had to go back to a previous version.

**Comment by vacoj** [comment] 2016-03-22 06:38
Thanks for maintaining this repo.  Same suspend issue here.  Ended up rolling back to 4.3-2 for the time being.

**Comment by raphael** [comment] 2016-03-24 14:47
I reverted to release 4.4-6 which runs 4.4.2. Both in this repo and in the AUR. I'm looking at 4.5 but it has the same suspend issue. Also sound is not working in 4.5, see http://stackoverflow.com/questions/36193860/issue-with-alsa-soc-codec-devm-gpiod-get-index-fails. I'll leave this issue openened until it is fixed in the latest.

**Comment by markiaindean** [comment] 2016-03-25 12:27
I have the suspend issue in 4.4.5 but have the sound working.  I had to manually change the /etc/pulse/default.pa file as directed in the lines:

load-module module-alsa-source device=hw:0,1
load-module module-alsa-source device=hw:0,2
load-module module-alsa-sink device=hw:0,0

Restart and then run the following from the ~/linux-samus/scripts/setup/sound directory:

ALSA_CONFIG_UCM=ucm/ alsaucm -c bdw-rt5677 set _verb HiFi

I had to be in the sound directory or it would return errors.  

I then installed pavucontrol to switch the application sound output to the right output device bdw-rt5677 or HDMI.  Sound then worked.

**Comment by markiaindean** [comment] 2016-03-25 12:28
OK, just realised you guys are a version ahead of me ... sorry

**Comment by Friz-zy** [comment] 2016-05-08 18:43
Hi guys,

I got this bug with patched ubuntu 4.4.0-17-generic kernel. Only sound config section was from @raphael config.

There is a good manual: [Best practice to debug Linux* suspend/hibernate issues](https://01.org/blogs/rzhang/2015/best-practice-debug-linux-suspend/hibernate-issues).

`echo freeze > /sys/power/state` works fine so as temporary solution we can [use it as custom script for some actions](https://askubuntu.com/questions/3294/setup-suspend-on-lid-close-fnf4-outside-of-kde-gnome). Unfortunately I don't know how to override default gnome\kde power manager applets for using it as default suspend actions. `pm-suspend` works only with ram suspend.

Ram suspend fails when tried resume\load alsa modules. I saw message about some null pointer bug in debug, but I can't save output from tty in debug mode. We can create custom pm hook for suspend\resume if someone help me with loading alsa modules without reboot. I tried `alsa reload` and so on but then `aplay -l` freezes hard and then alsa, pulseaudio and system dosn't see any devices at all, even default hdmi =(

**Comment by hyena** [comment] 2016-07-15 04:36
Been trying various versions and tags and still having a lot of issues with this. If suspending is working correctly on lid-close for anyone, can you please provide the kernel number and the tag id you used?

**Comment by vacoj** [comment] 2016-07-15 15:38
hyena, I was having some touchpad issues with 4.3.2, so I tested a bunch (it was really bothering me).  Ended up using 4.4.2-6ph and having no problems with suspend nor inputs.  Not really sure why it suddenly worked after rotating through a few kernels.

**Comment by hyena** [comment] 2016-07-15 22:16
I ended up doing a clean re-install of Xubuntu 16.04 and this time master (kernel 4.4.2ph+) has been suspending fine. The only difference I can think of is last time I ran `apt-get dist-upgrade` and I've held off on that this time around.

**Closed** 2016-08-24 20:17 UTC
