### ISSUE TITLE
Slackware dmesg error

### ISSUE THREAD

**Issue by bpeck1101** [raphael/linux-samus#17] opened 2015-07-17 04:13 UTC
I've been using Slackware since I got this laptop, and have everything working excluding sound, and some button issues. I used the kernel source you provided with a .config I was using for the vanilla 4.1 kernel, along with the bdw-rt5677 module. I copied the contents of firmware into /lib/firmware and /lib/firmware/intel just to make sure, and built the kernel along with modules. I was able to reboot and run just as I was before, but receive this dmesg error. 

[    0.695047] bdw-rt5677 bdw-rt5677: ASoC: CPU DAI spi-RT5677AA:00 not registered

aplay -l does not show the sound card for this reason, and I'm currently unable to determine why I receive that error. 

Also want to note Slackware does not have pulse audio by default, from reading the page I only see it being required for the microphone.

**Comment by raphael** [comment] 2015-07-17 07:38
This error looks like the driver modules may not be loaded. What does `lsmod | grep bdw` return? should be:
```
➜  activity_service_v2 git:(go_activity_service) ✗ lsmod | grep bdw
snd_soc_sst_bdw_rt5677_mach     7593  2
snd_soc_sst_haswell_pcm    44897  4 snd_soc_sst_bdw_rt5677_mach
snd_soc_rt5677        163345  5 snd_soc_sst_bdw_rt5677_mach
snd_soc_core          128251  6 snd_soc_rt5677,snd_soc_rt5677_spi,snd_soc_sst_haswell_pcm,snd_soc_sst_bdw_rt5677_mach
```

**Comment by bsd1101** [comment] 2015-07-17 15:49
I get 

snd_soc_sst_bdw_rt5677_mach     7881  0 
snd_soc_sst_haswell_pcm    59868  1 snd_soc_sst_bdw_rt5677_mach
snd_soc_rt5677        163761  1 snd_soc_sst_bdw_rt5677_mach
snd_soc_core          133662  4 snd_soc_rt5677,snd_soc_rt5677_spi,snd_soc_sst_haswell_pcm,snd_soc_sst_bdw_rt5677_mach

**Comment by raphael** [comment] 2015-07-17 17:47
ok then my next guess would be the firmware, what does `dmesg | grep firmware` return and `dmesg | grep bdw`

**Comment by bsd1101** [comment] 2015-07-17 17:50
firmware returns wifi, bluetooth and trackpad

bdw returns nothing

**Comment by raphael** [comment] 2015-07-18 04:11
Is this using your own `.config` ? there are a number of options that need to be enabled for the sound to work. Would you mind trying with the `.config` that is included in this repo? also wrt "bdw returned nothing" - it must have returned the error message above, might be helpful to see the exact output of the grep command.

**Comment by bsd1101** [comment] 2015-07-18 06:36
with that config the screen does not turn on during boot. I've tried changing a few gfx options and building from scratch, but no go...

**Comment by raphael** [comment] 2015-07-18 06:54
I doubt the problem is the config (using it just fine as is anyone using the packages built in this repo). Maybe something is up with the boot loader?

**Comment by bsd1101** [comment] 2015-07-18 06:58
if it was the boot loader wouldn't none of my configs and/or built kernel.s work?

**Comment by raphael** [comment] 2015-07-18 07:27
I'm stumped. I'd try removing all the installed modules, compile the kernel clean, then install the modules and kernel (via `make module_install` and `make install`). Regenerate the grub config and reboot. I just pushed some  changes to upgrade the kernel to v4.1.2, maybe try pulling latest first.

**Comment by bsd1101** [comment] 2015-07-18 22:51
Now I'm stumped. I've been rebuilding the kernel with slightly different configs over and over. Cannot get the video to work on startup; although I've been checking /var/log/messages and realized it's not just the video drivers. Nothing posts with that config. I need to find what changes in your config are causing this to happen. 

Just to make sure: I don't need to run anything from the scripts folder correct? The kernel in /build/linux and the config you provided should create a working kernel ?

**Comment by raphael** [comment] 2015-07-19 17:25
The provided build/linux tree including the config is what is used to build the packages. It ought to "just work". What partitioning scheme are you using? are you using LVM? disk encryption? anything else "special" with your partition setup?

**Comment by bsd1101** [comment] 2015-07-19 17:45
home and swap are encrypted, but all the modules for that are included in your config

**Comment by raphael** [comment] 2015-08-04 00:44
@bsd1101 is this still an issue with the latest release?

**Comment by bsd1101** [comment] 2015-08-04 03:23
will try tomorrow.

**Comment by raphael** [comment] 2015-08-05 03:41
Would you mind describing the steps you are taking to install the kernel?

**Comment by bsd1101** [comment] 2015-08-05 04:24
cp the contents of build linux into  /usr/src/samus
ln -s samus linux

remove .config link that is now broken 
cp the config from the scripts directory to a .conf in /usr/src/samus

make -j4 bzImage modules 

cp arch/x86/boot/bzImage /boot/x
make modules_install
cp System.map /boot/System.map
lilo

works with all the vanilla kernels.

**Comment by raphael** [comment] 2015-08-05 07:40
The build steps you listed above seem OK to me as well. The fact that nothing happens could indicate an issue with the bootloader. I'm wondering if you need to rebuild your initramfs after installing the kernel - not sure which method Slackware uses to do that, seems like `mkinitrd`. The script that installs the kernel on ArchLinux has a post install step that runs `depmod` followed by `mkinitcpio` (https://github.com/raphael/linux-4.1-samus/blob/master/scripts/archlinux/linux.install#L7-L13).

**Comment by bsd1101** [comment] 2015-08-05 11:01
will mkinitrd in a few hours and let you know.

**Comment by bsd1101** [comment] 2015-08-05 13:44
made initrd, no change :( I'm asking in Slackware irc for suggestions. This ain't over till I get it working :)

**Comment by raphael** [comment] 2015-08-05 15:20
:-) thanks for looking into it.

**Comment by raphael** [comment] 2015-09-01 17:51
Any luck with this? is that still an issue with the latest?

**Comment by bsd1101** [comment] 2015-09-04 02:59
still have the same issue. If I use your config without modification kernel doesn't post. If I use my own kernel that works with 4.2 I get bdw-rt5677 bdw-rt5677: ASoC: CPU DAI spi-RT5677AA:00 not registered multiple times

**Comment by bpeck1101** [comment] 2015-09-14 22:44
so https://github.com/jakeday/chromebook-pixel-slackware gets me to load the module correctly yet I still don't have sound. Messing with those options now...

**Comment by raphael** [comment] 2015-09-18 07:10
These don't sound like issues with the kernel. Different volume in different apps sound more like an issue at the PulseAudio level. I'd check the sound settings (e.g. in KDE one must make sure the application is associated with the right "channel" i.e. speaker vs earphone vs HDMI). I'm closing this issue as I'm not sure there's much value in leaving it open. Feel free to re-open with more info.

**Closed by raphael** 2015-09-18 07:10 UTC
