### ISSUE TITLE
Getting lots of module errors

### ISSUE THREAD

**Issue by penetrance** [raphael/linux-samus#151] opened 2016-08-17 17:10 UTC
When I try to install on a fresh Gallium OS 2.0 install, I get these errors and then I can't boot into my system after a restart and have to reinstall Gallium OS.

linux-samus/build/debian$ sudo dpkg -i *.deb
Selecting previously unselected package linux-firmware-image-4.7.1-ph+.
(Reading database ... 196456 files and directories currently installed.)
Preparing to unpack linux-firmware-image-4.7.1-ph+_4.7.1-ph+-1_amd64.deb ...
Unpacking linux-firmware-image-4.7.1-ph+ (4.7.1-ph+-1) ...
Selecting previously unselected package linux-headers-4.7.1-ph+.
Preparing to unpack linux-headers-4.7.1-ph+_4.7.1-ph+-1_amd64.deb ...
Unpacking linux-headers-4.7.1-ph+ (4.7.1-ph+-1) ...
Selecting previously unselected package linux-image-4.7.1-ph+.
Preparing to unpack linux-image-4.7.1-ph+_4.7.1-ph+-1_amd64.deb ...
Unpacking linux-image-4.7.1-ph+ (4.7.1-ph+-1) ...
Preparing to unpack linux-libc-dev_4.7.1-ph+-1_amd64.deb ...
Unpacking linux-libc-dev (4.7.1-ph+-1) over (4.7-galliumos0+dev1) ...
Setting up linux-firmware-image-4.7.1-ph+ (4.7.1-ph+-1) ...
Setting up linux-headers-4.7.1-ph+ (4.7.1-ph+-1) ...
Setting up linux-image-4.7.1-ph+ (4.7.1-ph+-1) ...
update-initramfs: Generating /boot/initrd.img-4.7.1-ph+
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/common/usb-common.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/core/usbcore.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/host/ehci-hcd.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/host/ehci-pci.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/host/ohci-hcd.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/host/ohci-pci.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/host/uhci-hcd.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/hid/hid.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/hid/usbhid/usbhid.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/host/xhci-hcd.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/usb/host/xhci-pci.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/lib/raid6/raid6_pq.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/crypto/xor.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/btrfs/btrfs.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/mbcache.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/jbd2/jbd2.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/lib/crc16.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/ext4/ext4.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/isofs/isofs.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/jfs/jfs.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/reiserfs/reiserfs.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/squashfs/squashfs.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/lib/crc-itu-t.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/udf/udf.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/arch/x86/crypto/crc32c-intel.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/crypto/crc32c_generic.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/lib/libcrc32c.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/xfs/xfs.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/fscache/fscache.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/net/sunrpc/sunrpc.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/nfs_common/grace.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/lockd/lockd.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/nfs/nfs.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/nfs/nfsv2.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/nfs_common/nfs_acl.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/nfs/nfsv3.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/net/dns_resolver/dns_resolver.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/nfs/nfsv4.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/input/serio/serio.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/input/serio/i8042.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/input/serio/libps2.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/input/keyboard/atkbd.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/input/mouse/psmouse.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/virtio/virtio.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/virtio/virtio_ring.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/virtio/virtio_pci.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/virtio/virtio_mmio.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/fat/fat.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/fat/vfat.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/nls/nls_cp437.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/nls/nls_iso8859-1.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/scsi/scsi_mod.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/message/fusion/mptbase.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/message/fusion/mptscsih.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/scsi/scsi_transport_fc.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/message/fusion/mptfc.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/scsi/scsi_transport_sas.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/message/fusion/mptsas.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/scsi/scsi_transport_spi.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/message/fusion/mptspi.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/hv/hv_vmbus.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/hv/hv_utils.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/net/hyperv/hv_netvsc.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/scsi/hv_storvsc.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/input/serio/hyperv-keyboard.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/lib/842/842_decompress.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/dm-mod.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/dm-crypt.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/dm-log.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/dm-region-hash.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/dm-mirror.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/video/vgastate.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/video/fbdev/vga16fb.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/fs/fuse/fuse.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/acpi/fan.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/acpi/thermal.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/dm-bufio.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/dm-snapshot.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/crypto/async_tx/async_tx.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/crypto/async_tx/async_xor.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/crypto/async_tx/async_pq.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/crypto/async_tx/async_memcpy.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/crypto/async_tx/async_raid6_recov.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/md-mod.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/raid456.ko.gz not found.
modinfo: ERROR: Module /lib/modules/4.7.1-ph+/kernel/drivers/md/dm-raid.ko.gz not found.
Generating grub configuration file ...
Warning: Setting GRUB_TIMEOUT to a non-zero value when GRUB_HIDDEN_TIMEOUT is set is no longer supported.
Found linux image: /boot/vmlinuz-4.7.1-ph+
Found initrd image: /boot/initrd.img-4.7.1-ph+
Found linux image: /boot/vmlinuz-4.7.0-galliumos
Found initrd image: /boot/initrd.img-4.7.0-galliumos
Found linux image: /boot/vmlinuz-4.4.6-galliumos
Found initrd image: /boot/initrd.img-4.4.6-galliumos
Found memtest86+ image: /memtest86+.elf
Found memtest86+ image: /memtest86+.bin
done
Setting up linux-libc-dev (4.7.1-ph+-1) ...

**Comment by chepurko** [comment] 2016-08-18 19:56
I can confirm I'm getting the same module errors as the comment above. The strange things is that the files that it says are not found do in fact exist but `modinfo` does not see them apparently. Then on boot up I get the following error and I can't start with this kernel;

`/scripts/init-top/unbind-ehci: line 15: can't create /sys/bus/pci/drivers/ehci-pci/unbind: nonexistent directory`

But again, the referenced directory does exist on my system.

P.S. @penetrance it's not necessary to reinstall your entire OS. When you install a new kernel it doesn't uninstall your old ones automatically. You can always load the previously working older kernel from the GRUB menu > Advanced options (which is what I did). Then you can just uninstall the new non-working kernel. I know Gallium OS disables the GRUB menu by default but try the recovery mode or something and boot into the old kernel or just uninstall the new non-working one and you should be back to normal.

**Comment by raphael** [comment] 2016-08-18 21:52
hmm could you try disabling module compression? (`Enable loadable module support -----> Compress modules on installation`). That is clone the repo, run `make nconfig` in the `build/linux` directory edit the option and rebuild / reinstall the kernel.

**Comment by chepurko** [comment] 2016-08-18 22:01
When I run `make nconfig` in the `build/linux` directory I get a fatal error:

`  HOSTCC  scripts/kconfig/nconf.o
In file included from scripts/kconfig/nconf.c:13:0:
scripts/kconfig/nconf.h:18:20: fatal error: curses.h: No such file or directory
compilation terminated.
scripts/Makefile.host:108: recipe for target 'scripts/kconfig/nconf.o' failed
make[1]: *** [scripts/kconfig/nconf.o] Error 1
Makefile:544: recipe for target 'nconfig' failed
make: *** [nconfig] Error 2`

BTW I've never complied and installed kernels from source so I have little knowledge about it.

**Comment by chepurko** [comment] 2016-08-18 23:02
Welp, there goes my Xubuntu installation! 😄 After poking around and finally figuring out how to successfully complete `sudo make install`, I restarted and I can't boot past SeaBios or even the the GRUB menu to try a different kernel. How the heck did that happen?

Here's what I had to do to successfully compile and install the kernel:

```
$ sudo apt install libncurses5-dev lzop
$ git clone --depth=1 https://github.com/raphael/linux-samus
$ cd linux-samus/build/linux
$ make nconfig
```
The I disabled module compression (`Enable loadable module support -----> Compress modules on installation`)
```
$ make -j4
$ sudo make modules_install
$ make bzImage
$ sudo make install
```
So now I guess i'm back to Chrome OS...

**Comment by reynhout** [comment] 2016-08-18 23:26
@penetrance there's a test kernel 4.7 for GalliumOS that includes the audio patches. Check the comments on the other issue tracker.

**Comment by chepurko** [comment] 2016-08-19 23:44
I've started over with a fresh GalliumOS install on the entire disk. I just tried to install the `linux-image-4.7.1-ph+` again and I am getting the same module errors as above.

Needless to say I'm sceptical of redoing my previous steps of re-compiling and re-installing the kernel because I don't want to start all over again. Any chance we figure this out and we can get new binary packages?

**Comment by chepurko** [comment] 2016-08-20 20:15
Just ran the kernel compilation again on my fresh GalliumOS 2 install and it worked. I did not have to do the `make bzImage` this time.

The only issue I'm having is sound not working as described [in this issue](https://github.com/raphael/linux-samus/issues/150).

So is it safe to say that the module compression in the deb packages is what breaks installation on at least some machines?

**Comment by reynhout** [comment] 2016-08-20 20:53
@chepurko just to make sure: do you need additional kernel config over what the GalliumOS kernel provides (aside from working audio)? If not, there's a GalliumOS kernel with working SAMUS audio in the galliumos-testing repo.

**Comment by raphael** [comment] 2016-08-20 21:13
@chepurko I don't understand why the kernel packaged for Debian would fail to load compressed modules but it does seem to be the problem. I'll build the next release without compressed models.

**Comment by chepurko** [comment] 2016-08-20 22:09
@raphael I'm wondering if this occurred only on my machine and the OP's or on many other Debian/Ubuntu users.

@reynhout I don't need additional config besides audio. I didn't know about the galliumos-testing repo, do you have any links? I guess I would add the repo to my sources.lst?

**Comment by raphael** [comment] 2016-08-20 23:26
I just pushed release v4.7-3 which upgrades to Linux v.4.7.2 and does not compress modules on installation.

**Comment by reynhout** [comment] 2016-08-21 00:07
@chepurko see https://github.com/GalliumOS/galliumos-distro/issues/100#issuecomment-241174776

@raphael sorry for distracting, just want to keep GalliumOS users in the least-complicated config that will work for them. :)

**Comment by chepurko** [comment] 2016-08-21 06:53
Installation worked fine with v4.7.2, thanks. Can probably close this now.

**Comment by raphael** [comment] 2016-08-21 16:18
@reynhout, no problem. Will have to take a look at the Gallium kernel.

**Closed by raphael** 2016-08-21 16:18 UTC
